# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pcdaten\searchuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchUser(object):
    def setupUi(self, searchUser):
        searchUser.setObjectName("searchUser")
        searchUser.resize(400, 248)
        self.gridLayout = QtWidgets.QGridLayout(searchUser)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(searchUser)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.lineSearchUser = QtWidgets.QLineEdit(searchUser)
        self.lineSearchUser.setObjectName("lineSearchUser")
        self.gridLayout.addWidget(self.lineSearchUser, 1, 0, 1, 1)
        self.searchUsers = QtWidgets.QPushButton(searchUser)
        self.searchUsers.setObjectName("searchUsers")
        self.gridLayout.addWidget(self.searchUsers, 1, 1, 1, 1)
        self.listUsers = QtWidgets.QListView(searchUser)
        self.listUsers.setObjectName("listUsers")
        self.gridLayout.addWidget(self.listUsers, 2, 0, 1, 2)

        self.retranslateUi(searchUser)
        QtCore.QMetaObject.connectSlotsByName(searchUser)

    def retranslateUi(self, searchUser):
        _translate = QtCore.QCoreApplication.translate
        searchUser.setWindowTitle(_translate("searchUser", "Form"))
        self.label.setText(_translate("searchUser", "Name und Vorname eingeben:"))
        self.searchUsers.setText(_translate("searchUser", "PushButton"))
