# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pcdaten\setuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setUser(object):
    def setupUi(self, setUser):
        setUser.setObjectName("setUser")
        setUser.resize(400, 319)
        self.formLayout = QtWidgets.QFormLayout(setUser)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(setUser)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(setUser)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_7 = QtWidgets.QLabel(setUser)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.surName = QtWidgets.QLineEdit(setUser)
        self.surName.setObjectName("surName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.surName)
        self.telNum = QtWidgets.QLineEdit(setUser)
        self.telNum.setObjectName("telNum")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.telNum)
        self.department = QtWidgets.QLineEdit(setUser)
        self.department.setObjectName("department")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.department)
        self.room = QtWidgets.QLineEdit(setUser)
        self.room.setObjectName("room")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.room)
        self.ndsId = QtWidgets.QLineEdit(setUser)
        self.ndsId.setObjectName("ndsId")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.ndsId)
        self.insertData = QtWidgets.QPushButton(setUser)
        self.insertData.setObjectName("insertData")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.insertData)
        self.label_8 = QtWidgets.QLabel(setUser)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.archiv24User = QtWidgets.QCheckBox(setUser)
        self.archiv24User.setText("")
        self.archiv24User.setChecked(False)
        self.archiv24User.setObjectName("archiv24User")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.archiv24User)
        self.label = QtWidgets.QLabel(setUser)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.firstName = QtWidgets.QLineEdit(setUser)
        self.firstName.setObjectName("firstName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.firstName)
        self.label_6 = QtWidgets.QLabel(setUser)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(setUser)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(setUser)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.persID = QtWidgets.QLineEdit(setUser)
        self.persID.setObjectName("persID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.persID)
        self.label_9 = QtWidgets.QLabel(setUser)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)

        self.retranslateUi(setUser)
        QtCore.QMetaObject.connectSlotsByName(setUser)

    def retranslateUi(self, setUser):
        _translate = QtCore.QCoreApplication.translate
        setUser.setWindowTitle(_translate("setUser", "Form"))
        self.label_2.setText(_translate("setUser", "Nachname:"))
        self.label_3.setText(_translate("setUser", "TelefonNr."))
        self.label_7.setText(_translate("setUser", "Nutzerkennung"))
        self.insertData.setText(_translate("setUser", "Einfügen"))
        self.label_8.setText(_translate("setUser", "Archiv 24 Benutzer"))
        self.label.setText(_translate("setUser", "Vorname"))
        self.label_6.setText(_translate("setUser", "Abteilung"))
        self.label_5.setText(_translate("setUser", "Raum"))
        self.label_4.setText(_translate("setUser", "Pers_ID"))
