# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pcdaten\setuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setUser(object):
    def setupUi(self, setUser):
        setUser.setObjectName("setUser")
        setUser.resize(400, 319)
        self.formLayout = QtWidgets.QFormLayout(setUser)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(setUser)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(setUser)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_7 = QtWidgets.QLabel(setUser)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(setUser)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(setUser)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(setUser)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(setUser)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(setUser)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.pushButton = QtWidgets.QPushButton(setUser)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_8 = QtWidgets.QLabel(setUser)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.checkBox = QtWidgets.QCheckBox(setUser)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.label = QtWidgets.QLabel(setUser)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_4 = QtWidgets.QLineEdit(setUser)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtWidgets.QLabel(setUser)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(setUser)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(setUser)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(setUser)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_9 = QtWidgets.QLabel(setUser)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)

        self.retranslateUi(setUser)
        QtCore.QMetaObject.connectSlotsByName(setUser)

    def retranslateUi(self, setUser):
        _translate = QtCore.QCoreApplication.translate
        setUser.setWindowTitle(_translate("setUser", "Form"))
        self.label_2.setText(_translate("setUser", "Nachname:"))
        self.label_3.setText(_translate("setUser", "TelefonNr."))
        self.label_7.setText(_translate("setUser", "Nutzerkennung"))
        self.pushButton.setText(_translate("setUser", "PushButton"))
        self.label_8.setText(_translate("setUser", "Archiv 24 Benutzer"))
        self.label.setText(_translate("setUser", "Vorname"))
        self.label_6.setText(_translate("setUser", "Abteilung"))
        self.label_5.setText(_translate("setUser", "Raum"))
        self.label_4.setText(_translate("setUser", "Pers_ID"))
